const GET_PROFILE_KEY = 'GET_PROFILE_KEY';

const GET_FOLLOWERS_KEY = 'GET_FOLLOWERS_KEY';
const GET_FOLLOWING_KEY = 'GET_FOLLOWING_KEY';

export { GET_PROFILE_KEY, GET_FOLLOWERS_KEY, GET_FOLLOWING_KEY };
